### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ChrisBriggsy** [SSWConsulting/musicstore-ui-angular2-dotnet#1]
When I try to run the Music Store web UI, i am finding that angle brackets are not being correctly replaced.

![image](https://cloud.githubusercontent.com/assets/2142485/11520950/9eda0130-98f3-11e5-9edd-ce3369b4c27e.png)

Also Visual studio the syntax appears to causes

**Comment by adamstephensen** [comment]
Thanks Chris. This was resolved
