### ISSUE TITLE
BUG Angular2-JWT dependency version 0.1.14+ targets Angular 2.0.0-rc

### ISSUE THREAD

**Issue by careLearning** [SSWConsulting/musicstore-ui-angular2-dotnet#18]
The following errors (see screenshots) occur on compilation, building, and execution:

`tsc`
![tsc](https://cloud.githubusercontent.com/assets/15213955/15276646/235a11b2-1abc-11e6-8f66-66c1fa654965.png)

`gulp build`
![gulp](https://cloud.githubusercontent.com/assets/15213955/15276647/2782bca8-1abc-11e6-84b4-6910ceebc6b7.png)

**chrome dev tools**
![chrome](https://cloud.githubusercontent.com/assets/15213955/15276648/2ab1d71a-1abc-11e6-806a-311ee5d018a8.png)
## FIX
-  `npm i angular2-jwt@0.1.13 -S`
-  or remove the caret **^** from the _angular2-jwt_ dependency in the _package.json_.

**Comment by gonzigonz** [comment]
Thanks that worked.

**Comment by fenix2222** [comment]
Will be fixed after pull request #28 is approved
