### ISSUE TITLE
Error when i run the NPM install command - Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.

### ISSUE THREAD

**Issue by ChrisBriggsy** [SSWConsulting/musicstore-ui-angular2-dotnet#2]
I cloned the Music Store Repo, followed the instructions provided and when I ran the NPM install command. The following error appeared: 

_node-sass@3.4.2 postinstall script 'node scripts/build.js'_

![image](https://cloud.githubusercontent.com/assets/2142485/11520258/8843c1fa-98ed-11e5-9ed8-7ab8138ca74f.png)

**Comment by adamstephensen** [comment]
Hi Chris, thanks for the feedback.
This has been resolved by the new setup config
