### ISSUE TITLE
issue with typings install

### ISSUE THREAD

**Issue by minuz** [SSWConsulting/musicstore-ui-angular2-dotnet#24]
Hi guys, I've been trying to run this app as part of my angular learning and I got stucked on the following:
After running npm install, the messages were saying that the post install script "typings install" failed.

I have the same issue on both Mac and Windows. 
When checking the version of the following 
    node v4.4.7
    npm 2.15.8
    dnvm 1.0.0-rc2-15546
    tsc 1.8.10
    gulp 3.9.1 

The error message is: 

λ typings install
typings ERR! message Attempted to compile "moment" as an external module, but it looks like a global module. You'll need to enable the global option to continue.

typings ERR! cwd C:\Users\fernando.baba\Documents\My Web Sites\enterprise-musicstore-ui-angular2\src\SSW.MusicStore.Web
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\fernando.baba\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install"
typings ERR! node -v v4.4.7
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

What am I missing??

**Comment by fenix2222** [comment]
Will be fixed after pull request #28 is approved
