### ISSUE TITLE
Error TS2322 Type 'Observable<any[]>' is not assignable to type 'Observable<any[]>'.

### ISSUE THREAD

**Issue by ChrisBriggsy** [SSWConsulting/musicstore-ui-angular2-dotnet#3]
I cloned the Music Store Repos, followed the instructions provided and am noticing i have a lot of typescript errors being displayed in visual studio. Upon investigation it appears these errors are all connected to the use of Observable throughout the application 

_Severity Code Description Project File Line Suppression State
Error TS2322 Type 'Observable<any[]>' is not assignable to type 'Observable<any[]>'.
  Types of property 'source' are incompatible.
    Type 'Observable<any>' is not assignable to type 'Observable<any>'. TypeScript Virtual Projects C:\ChrisBriggsyGit\musicstore-ui-angular2-dotnet\src\SSW.MusicStore.Web\app\services\album\album.service.ts_

![image](https://cloud.githubusercontent.com/assets/2142485/11520135/26eace90-98ec-11e5-8697-20cf7a46e658.png)

**Comment by fenix2222** [comment]
Fixed
