### ISSUE TITLE
Error when i run the NPM install command - Failed at the ssw-musicstore@0.0.0 postinstall script 'tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall'

### ISSUE THREAD

**Issue by ChrisBriggsy** [SSWConsulting/musicstore-ui-angular2-dotnet#4]
I cloned the Music Store Repo, followed the instructions provided and when I ran the NPM install command. The following error appeared: 

_Failed at the ssw-musicstore@0.0.0 postinstall script 'tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall'_

![npm issues](https://cloud.githubusercontent.com/assets/2142485/11519990/c4a331ba-98ea-11e5-8c2d-a0bc79354632.png)

**Comment by fenix2222** [comment]
Fixed
